### PR TITLE
Some modernization & code cleanup

### PR DESCRIPTION
**Pull request by mary-kate**
Note that this bumps the minimum required MediaWiki version to 1.25 or newer.

### CODE REVIEW

**Comment by troyengel** [comment]
I pulled a git clone off your master branch (easier :)) onto my own wiki, which is running... 1.25.6 (I don't update that often, sorry - it works!) and it doesn't seem to be working at all. The extension loads and shows the new version in Special:Version (good), and there are zero errors in the logfiles (the usual php stuff) so it's not a typo or failure at that level. The content of my new edit is just... not there.

My LocalSettings.php:
```
wfLoadExtension( 'Preloader' );
...
$wgPreloaderSource[NS_MAIN] = 'Template:Boilerplate';
```
Here's the content of that template:
```
<includeonly>
{{DISPLAYTITLE:Article Title}}
__TOC__


== Overview ==


{{bc|1=<nowiki>
</nowiki>}}


[[Category:Linux]]
</includeonly>
<noinclude>
This template is included by the Preloader extension on new article creation.
</noinclude>
```
Any idea why it won't load the template with all your changes? I have the two clones side by side, simply renaming the directories back and forth shows working/not-working (easy to replicate), just no apparent logs or errors of what's not working. Any chance you used a feature 1.25.6 doesn't support?

**Comment by mary-kate** [comment]
Thanks for testing this one out! Seems that I was overcomplicating a few things while also missing out a few obvious ones. The latest patch should fix it so that defining `$wgPreloaderSource` works again. Can you test it out, please? :)

For reference, here's a very handy manual page on MediaWiki.org that I really should've read the first time around: https://www.mediawiki.org/wiki/Manual:Extension.json/Schema (especially the `config` section!)

(Judging by your comment, I take it that you're familiar with the [version lifecycle](https://www.mediawiki.org/wiki/Version_lifecycle) page and you know that 1.25 has reached its end-of-life a while ago, right? You should consider updating to 1.27 or 1.28 -- depending on what, if any, authentication-related extensions you're using, it can be a very smooth ride...or an annoyingly bumpy one, as 1.27 changes a lot of the authentication internals; there's some documentation about that on MediaWiki.org, see [Manual:SessionManager and AuthManager](https://www.mediawiki.org/wiki/Manual:SessionManager_and_AuthManager)).

**Comment by troyengel** [comment]
Everything seems to work fine now, no errors in the log. It also works if you don't upgrade LocalSettings.php to use wfLoadExtension, the require_once method is function so we don't break anyone's git pull from master. Go ahead and squash your commits down and I'll merge the PR as one commit.

On upgrading my mwiki, I'll get around to it - it's a pain in the ass because there's always something changed, deprecated and moved around so I just don't feel like dealing with it right now. Every major point release upgrade (I've done it like 10 times) ends up costing me hours and hours to sort out what stupid shit got broken and how to make it work the 'new' way, I lost interest in trying to keep up long ago and just let it run as-is.

**Comment by troyengel** [comment]
Friendly ping, waiting on a quick rebase/squash of commits to move forward. :)

**Comment by SamanthaNguyen** [comment]
@troyengel: Hi! @mary-kate gave me write access to her fork to help squash the commits into one, so it's all squashed now.

**Pull request merged**
